### ISSUE TITLE
Package does not install because of six version

### ISSUE THREAD

**Issue by Pluggi** [presslabs/pyolite#20]
Pyolite (v1.5.7) does not install on Arch Linux because of `six`, on a fresh install.
Arch Linux uses version 1.10.0, but Pyolite requires version 1.6.1.

It fails with

```
  Running setup.py install for spec ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-tzu08jgy/spec/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-1nuq9k4s-record/install-record.txt --single-version-externally-managed --compile:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 10, in <module>
        from setuptools.extern.six.moves import filter, map
      File "/usr/lib/python3.6/site-packages/setuptools/extern/__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 49, in <module>
        from pkg_resources.extern.six.moves import urllib, map, filter
    ModuleNotFoundError: No module named 'pkg_resources.extern.six.moves'; 'pkg_resources.extern.six' is not a package
```

**Comment by luisiacc** [comment]
try this: 
`pip install -U pip setuptools`, and then install
